### PR TITLE
build for py35 and py36

### PR DESCRIPTION
**Pull request by kiwi0fruit**
Some modules (panflute in particular) use shutilwhich even for py35 and py36. And this makes sense because "On Python 3.3 and above, the module never do anything but return the stdlib shutil.which function."

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
I've only made a tweak to the `recipe/meta.yaml`. But the other files should be automatically re-generated too...

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by kiwi0fruit** [comment]
I've tryed to rerender them myself... but installing conda-smithy broke my root conda (actually I updated conda to 4.4 so that's the reason).

**Comment by kiwi0fruit** [comment]
@ocefpaf Do you know whether `continuous-integration/appveyor/pr — AppVeyor build failed` is important and why did it fail?

**Comment by ocefpaf** [comment]
> I've tryed to rerender them myself... but installing conda-smithy broke my root conda (actually I updated conda to 4.4 so that's the reason).

Unfortunately `conda-smithy` is not 100% ready for `conda 4.4`, that is why re-rendering with the command above is recommend, so it is always perform via a "blessed" set of dependencies.

However, something is off with the Windows config. Let me try that locally, hold on...

**Pull request closed without merging**
