### PR TITLE
Build all pys

### PR DESCRIPTION
**Pull request by ocefpaf**
Alternative for #5
 
Ping @kiwi0fruit.

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
thanks! //Waiting for Travis CI...

**Comment by kiwi0fruit** [comment]
@ocefpaf For some reason only win versions were added:
https://anaconda.org/conda-forge/shutilwhich/files

**Comment by kiwi0fruit** [comment]
@ocefpaf Thanks for adding py35 and py36 support.

// other OS versions continue to appear. I guess it's not instant process.

**Comment by ocefpaf** [comment]
> // other OS versions continue to appear. I guess it's not instant process.

You can follow the upload via the CIs on master.

**Comment by kiwi0fruit** [comment]
@ocefpaf all buils on linux py35 on Windows failed. But pull #6 were succesful on every platform. I think I've read something about rebuilding if you you think that it's not your script fault... But I can't rememver where it was or what should I do.

**Comment by kiwi0fruit** [comment]
@ocefpaf Oh, found: https://github.com/kiwi0fruit/staged-recipes#11-some-checks-failed-but-it-wasnt-my-recipe-how-do-i-trigger-a-rebuild

Do I have rights to force push? As far as know I do not.

**Comment by ocefpaf** [comment]
Ideally you could add yourself as a maintainer to `shutilwhich`, by adding your GitHub handle to the list of maintainers, and then you could restart it yourself without a new PR.

I just restart it BTW, finger crossed!

**Comment by kiwi0fruit** [comment]
@ocefpaf whutilwhich will not be updated in any observable future (last update was in 2015 and it's a backport). So adding me as a maintainer is pointless here. But it would make sense in case of `panflute` and `pandoc-crossref`. Is adding my GitHub ID enough? Like this:
```yaml
extra:
  recipe-maintainers:
    - kiwi0fruit
```
?

**Comment by ocefpaf** [comment]
> Like this:
```yaml
extra:
  recipe-maintainers:
    - kiwi0fruit
```

Yep. That is pretty much it. Once merged you'll have to wait a bit and then the bots will give you access rights to the feedstock.

**Pull request merged**
